### ISSUE TITLE
Exception when running example splits: Failure "Hotkeys stream exited unexpectedly"

### ISSUE THREAD

**Issue by cassidoxa** [alexozer/flitter#12]
I've successfully built flitter but when I try to run `flitter splits.scm` with the example, I see the timer as it's shown in the screenshot for just a moment then get the following error:

```
Uncaught exception:
  
  (Failure "Hotkeys stream exited unexpectedly")

Raised at file "src/event_loop.ml", line 169, characters 4-241
Re-raised at file "src/core/lwt.ml", line 2987, characters 20-29
Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
Called from file "bin/main.ml", line 1, characters 9-23
```

I ran `opam list` and lwt is the latest version, 4.1.0. Also using opam 2.0.0 and ocaml 4.07.0 but on debian 9 stable. I installed opam manually from the unstable repo.

**Comment by cassidoxa** [comment]
That was the problem, thanks. I had Anaconda python in my path rather than the system's python so it couldn't find pynput. Simply had to remove it from my path and flitter works as intended.

**Comment by alexozer** [comment]
Great, glad to hear!
