### ISSUE TITLE
Are the keybindings configurable?

### ISSUE THREAD

**Issue by rosshadden** [alexozer/flitter#13]
I love (and need) the global hotkeys, but the specific keys used will never work for everyone. Are they configurable?

**Comment by alexozer** [comment]
Hi! I do agree that having something like a configuration file for keybindings and layout settings and such would be more ideal, unfortunately I don't have time to add major features to this timer at the moment.

I can try to give you an example of the kind of change you'd need to make to the code. You'd need to change [this function](https://github.com/alexozer/flitter/blob/master/src/event_loop.ml#L33-L137). For example, in the Idle state, if you wanted to change the keybindings from "q to quit, j or space to start" to "left shift to start, right alt to quit", you'd go from this:
```ocaml
| Idle -> (
        match key_str with
        | "space" | "j" -> {
            timer with
            state = Timing ([||], t)
          }
        | "q" -> raise Stdlib.Exit
        | _ -> timer
)
```

to this:

```ocaml
| Idle -> (
        match key_str with
        | "shift" -> {
            timer with
            state = Timing ([||], t)
          }
        | "alt_r" -> raise Stdlib.Exit
        | _ -> timer
)
```

So the keys for left shift, left alt etc are "shift", "alt", "ctrl", and for the right-side equivalents, they are "shift_r", "alt_r", "ctrl_r".

You'd have to make similar changes for the rest of the code block I linked in the previous reply. Afterwards, you can just compile and install Flitter like normal.

You can also use this script to discover which keycodes to use:

```python
import time
import sys
from pynput import keyboard


def on_press(key):
    try:
        t = time.time()
        try:
            # Alphanumeric key pressed
            print('{} {}'.format(t, key.char), flush=True)
        except AttributeError:
            # Special key pressed
            key_name = str(key)[4:] # Strip "Key."
            print('{} {}'.format(t, key_name), flush=True)
    except:
        sys.exit(0)

# Collect events until released
with keyboard.Listener(on_press=on_press) as listener:
    try:
        while True:
            t = time.time()
            print('{} heartbeat'.format(t))
            time.sleep(1)
    except:
        sys.exit(0)
listener.join()
```

**Comment by rosshadden** [comment]
That was sufficient for me, thanks. Unfortunately most special keys are recognized as `None` (likely an issue that should be filed with the key library you're using). Since I'm running a PC game with it's own mappings (doesn't even have that many, but also involves typing some arbitrary text) I struggled with finding keys that would work for me. I ended up using the F keys which were detected properly.

**Comment by alexozer** [comment]
Interesting, I tried myself and it seems that media keys are not recognized by this library. Thanks for pointing that out.

**Comment by hellstrike12** [comment]
Heya alexozer, i had an idea: what about using JSON or XML as a configuration file? I'm not a OCaml programmer, but i think that, if it's possible to implement, it would be a lot easier to tweak keybindings.

**Comment by alexozer** [comment]
I rewrote Flitter from scratch, and this has been addressed
