### ISSUE TITLE
dune build

### ISSUE THREAD

**Issue by dxtrm** [alexozer/flitter#14]
hi im having some issues

I have done all the steps up to the command `dune build` when I try it, it gives me `bash: /usr/bin/dune: No such file or directory` the only thing I havnt done is doing it as a root user 

if you can respond that would be great im trying to get into speed running

*update*
I realised I was dumb and I cloned and downloaded all the files but it still doesn't work
when I do `dune build` it gives me `The program 'dune' is currently not installed. You can install it by typing:
sudo apt install whitedune
`

**Comment by alexozer** [comment]
Hi! Did you install opam [as detailed here](https://opam.ocaml.org/doc/Install.html)? What's the output of `opam --version`?

Try restarting your terminal as well.

**Comment by alexozer** [comment]
Closing for low activity
