### ISSUE TITLE
After installing lwt_ppx, uutf, and uuseg, can't dune build due to some error

### ISSUE THREAD

**Issue by selplacei** [alexozer/flitter#20]
Followed the build instructions up until `dune build`. I manually installed the three missing libraries (as seen in other issues) but now I'm getting the following error:

    File "vendor/notty/lwt/notty_lwt.ml", line 68, characters 25-64:
    Error: This expression has type (unit -> unit) Lwt.t
           but an expression was expected of type unit Lwt.t
           Hint: Did you forget to provide `()' as argument?

I have absolutely no experience with OCaml so I don't know how to continue with this. Is there a workaround?

Edit: seems like PR #17 fixes this

**Comment by alexozer** [comment]
Fixed in 666c5483bc93efa6d01e0b7a927461269f8e14de.
