### ISSUE TITLE
Sum of best drops when I quit and relaunch flitter

### ISSUE THREAD

**Issue by burbruee** [alexozer/flitter#21]
Hi!
First of all, I just want to say that I love flitter and I think it's the best speedrun timer to use on linux.
I'm however experiencing an issue where the sum of best drops in time after I quit and relaunch flitter.

So as an example: I finished a run yesterday. Had a gold split and sum of best went down to 15:30.x (accurate) I press space after the run is done and the timer clears and everything looks good.
I press 'q' to quit. I then start flitter again and the layout now says the sum of best is 15:28.x

I'm not sure what the issue is.
Also the terminal I'm using to run flitter in is cool-retro-term to make it look a little nicer. Not sure if that's related to the issue, but after flitter has been running for a while and I quit it, there's some garbage output in the terminal upon exit.

Here is a twitch clip of it happening. I had just finished a run and the sum of best was 15:30. I quit flitter and cleared the garbage terminal output and restarted flitter and the sum of best went down to 15:28.

https://clips.twitch.tv/MoistKitschyGarlicNerfRedBlaster

Hoping to get this resolved so my golds can be accurate.
Thanks.

**Comment by alexozer** [comment]
Thanks for reporting, sorry you've experienced this!

I'm currently busy finishing up school for this semester so I don't have much time to work on this project much at the moment, but I'm hoping to get this repo cleaned up a bit in general at some point soon.

By the way, the timer looks great in cool-retro-term!
