### ISSUE TITLE
Opam switch error

### ISSUE THREAD

**Issue by david-simoes-93** [alexozer/flitter#24]
On a fresh Ubuntu 20.04 install, got this error

    $ opam switch 4.07.0
    [ERROR] No switch 4.07.0 is currently installed. Did you mean 'opam
        switch create 4.07.0'?
        Installed switches are:
          - default

Should the create option be used?

**Comment by stephencenter** [comment]
Yes, switch create worked for me!

**Comment by alexozer** [comment]
Fixed in 666c5483bc93efa6d01e0b7a927461269f8e14de.
