### ISSUE TITLE
dune build wont work

### ISSUE THREAD

**Issue by nimnim111** [alexozer/flitter#30]
typing dune build turns int this

File "src/dune", line 4, characters 53-64:
4 |   (libraries core lwt.unix notty notty.unix re color sexp_pretty)
                                                         ^^^^^^^^^^^
Error: Library "sexp_pretty" not found.
Hint: try: dune external-lib-deps --missing @@default

Trying the hint turn int this 

- color
- core
- lwt.unix
- lwt_ppx
- notty
- notty.unix
- ppx_sexp_conv
- re
- sexp_pretty
Hint: try: opam install color core lwt lwt_ppx notty ppx_sexp_conv re sexp_pretty

trying this hint leady to this

[NOTE] Package sexp_pretty is already installed (current version is v0.12.0).
[NOTE] Package re is already installed (current version is 1.9.0).
[NOTE] Package ppx_sexp_conv is already installed (current version is v0.12.0).
[NOTE] Package notty is already installed (current version is 0.2.2).
[NOTE] Package lwt_ppx is already installed (current version is 2.0.1).
[NOTE] Package lwt is already installed (current version is 5.4.0).
[NOTE] Package core is already installed (current version is v0.12.4).
[NOTE] Package color is already installed (current version is 0.2.0).

If I try dune build again I get the same problem over and over again even if i close and reopen the terminal 
I'm in ubuntu linux

**Comment by alexozer** [comment]
Which Ubuntu version are you on? `uname -a`

**Comment by Zenzou** [comment]
I'm getting the same error on Ubuntu 20.04/Pop_OS!

**Comment by virivongithub** [comment]
i'm having the same issue on ar(ch) tix 5.12.2-artix1-1

**Comment by virivongithub** [comment]
update: i was able to fix this by installing the opam package "depext" hope this helps

**Comment by Malwprotector** [comment]
Hi, I have the same problem. I've tried to reinstall opam, but nothing I have tried works. I get this error when I run `dune build` :
`File "src/dune", line 4, characters 53-64:`
`4 |   (libraries core lwt.unix notty notty.unix re color sexp_pretty)`
                                                         `^^^^^^^^^^^`
`Error: Library "sexp_pretty" not found.`
`Hint: try: dune external-lib-deps --missing @@default`
I don't understand why I get this error because sexp_pretty is already installed... when I run the command to install it, I am told that it is already installed.
I use Linux mint 20.3.
`Linux computer 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
Thanks for your help.
Ps: I've tried to install depext library, but I don't know how to use it... :(

**Comment by sleeplessKomodo** [comment]
`[jimbo@localhost flitter-master]$ opam install dune core lwt re color sexp_pretty uutf lwt_ppx uuseg notty
[NOTE] Package notty is already installed (current version is 0.2.2).
[NOTE] Package uuseg is already installed (current version is 15.0.0).
[NOTE] Package lwt_ppx is already installed (current version is 2.0.1).
[NOTE] Package uutf is already installed (current version is 1.0.3).
[NOTE] Package sexp_pretty is already installed (current version is v0.12.0).
[NOTE] Package color is already installed (current version is 0.2.0).
[NOTE] Package re is already installed (current version is 1.10.4).
[NOTE] Package lwt is already installed (current version is 5.5.0).
[NOTE] Package core is already installed (current version is v0.12.4).
[NOTE] Package dune is already installed (current version is 3.6.2).
[jimbo@localhost flitter-master]$ dune build
File "src/dune", line 4, characters 53-64:
4 |   (libraries core lwt.unix notty notty.unix re color sexp_pretty)
                                                         ^^^^^^^^^^^
Error: Library "sexp_pretty" not found.
-> required by library "flitter" in _build/default/src
-> required by executable main in bin/dune:2
-> required by _build/default/bin/main.exe
-> required by _build/install/default/bin/flitter
-> required by _build/default/flitter.install
-> required by alias install
-> required by alias default`

same issue, on Fedora 6.1.9-200.fsync.fc37.x86_64

**Comment by laszlostark** [comment]
I was having the exact same issues where the dependencies were showing up as missing even though they were installed through opam.

**I was able to solve the issue by running:**
`eval $(opam config env)`
in the terminal. After doing so, the build and install process finished without any problem.

Hope this helps

**Comment by alexozer** [comment]
I rewrote Flitter from scratch, and this is no longer an issue
