### ISSUE TITLE
opam switch create 4.07.0 not working

### ISSUE THREAD

**Issue by AjayAB** [alexozer/flitter#33]
I installed opam:
`user@dell-2017:~$ opam --version
`
`
2.0.8
`

ran opam init
but the next two commands didn't work
`user@dell-2017:~$opam switch create 4.07.0`
`[ERROR] No compiler matching '4.07.0' found, use 'opam switch list-available'
        to see what is available, or use '--packages' to select packages
        explicitly.
`
`user@dell-2017:~$  opam install dune core lwt re color sexp_pretty uutf lwt_ppx uuseg notty
[ERROR] No package named dune found.
[ERROR] No package named core found.
[ERROR] No package named re found.
[ERROR] No package named color found.
[ERROR] No package named sexp_pretty found.
[ERROR] No package named uutf found.
[ERROR] No package named lwt_ppx found.
[ERROR] No package named uuseg found.
[ERROR] No package named notty found.
`

**Comment by alexozer** [comment]
What's your Linux version? `uname -a`

**Comment by AjayAB** [comment]
hi,
I was on Ubuntu  18.04 . I just distrohopped into arch .
`[ajay@dellarch ~]$ uname --a`
`Linux dellarch 5.10.25-1-lts #1 SMP Sat, 20 Mar 2021 19:37:44 +0000 x86_64 GNU/Linux
`
in arch  , opam switch create 4.07.0 worked.
BUt dune build didn't work.
`[ajay@dellarch ~]$ cd flitter/`
`[ajay@dellarch flitter]$ dune build`
`bash: dune: command not found`
`[ajay@dellarch flitter]$ opam dune build`
`[ERROR] dune is not a known command or plugin (package dune.2.8.4 does not
        have the 'plugin' flag set).`
`[ajay@dellarch flitter]$ ls`
`LICENSE    bin  dune-project  flitter.install  src`
`README.md  doc  examples      flitter.opam`
`[ajay@dellarch flitter]$ dune build flitter.opam` 
`bash: dune: command not found`
`[ajay@dellarch flitter]$ opam dune build flitter.opam` 
`[ERROR] dune is not a known command or plugin (package dune.2.8.4 does not
        have the 'plugin' flag set).`
`[ajay@dellarch flitter]$ opam dune build flitter.install` 
`[ERROR] dune is not a known command or plugin (package dune.2.8.4 does not
        have the 'plugin' flag set).
`
I tried all of that ^ , but it didn't work.

**Comment by burbruee** [comment]
Did you do

`eval $(opam env)` ?

After that, dune should work.

**Comment by xRasea** [comment]
Could you add this to the readme? Worked for me. Thanks.

**Comment by alexozer** [comment]
I rewrote Flitter from scratch, and this is no longer an issue
