### ISSUE TITLE
Rerouting should not be so hard

### ISSUE THREAD

**Issue by MostAwesomeDude** [alexozer/flitter#40]
Currently, if I want to reroute, I have to hand-edit my file. I can use the [sexp](https://github.com/janestreet/sexp) utility to make it a little easier, but not by much.

I don't have any concrete requests yet, and I imagine that I could implement any features myself. This is more of a placeholder.

**Comment by alexozer** [comment]
The new JSON format may be a bit easier to manage. Closing for now.

**Comment by MostAwesomeDude** [comment]
I'll have to write up my solution so that I can share it with you. I hacked up a SQL schema that allows for multiple routes per category.
