### ISSUE TITLE
Timer doesn't show with many splits

### ISSUE THREAD

**Issue by kernel18** [alexozer/flitter#43]
Hi,
I was configuring my splits file for a run and wanted to test the display. But unfortunately, the main timer doesn't show, nor the splits are scrolling when I mark 2-Ca (in the example below) as complete... Is there a way to get around this ?
![image](https://user-images.githubusercontent.com/75426880/188316404-77e79efa-3bbc-4ce3-932a-ece839f5545e.png)

**Comment by alexozer** [comment]
I rewrote Flitter from scratch, and this is no longer an issue
