### ISSUE TITLE
flitter not found

### ISSUE THREAD

**Issue by bitWest11** [alexozer/flitter#44]
west@pop-os:~/flitter$ dune build
File "src/dune", line 5, characters 27-40:
5 |   (preprocess (pps lwt_ppx ppx_sexp_conv))
                               ^^^^^^^^^^^^^
Error: Library "ppx_sexp_conv" not found.
Hint: try:
  dune external-lib-deps --missing @@default

however, 

west@pop-os:~$ opam install dune core lwt re color sexp_pretty uutf lwt_ppx uuseg notty
[NOTE] Package notty is already installed (current version is 0.2.2).
[NOTE] Package uuseg is already installed (current version is 15.0.0).
[NOTE] Package lwt_ppx is already installed (current version is 2.0.1).
[NOTE] Package uutf is already installed (current version is 1.0.3).
[NOTE] Package sexp_pretty is already installed (current version is v0.12.0).
[NOTE] Package color is already installed (current version is 0.2.0).
[NOTE] Package re is already installed (current version is 1.10.4).
[NOTE] Package lwt is already installed (current version is 5.5.0).
[NOTE] Package core is already installed (current version is v0.12.4).
[NOTE] Package dune is already installed (current version is 3.7.0).

no package called external-lib-deps is available, and installing depext leaves me with nothing

west@pop-os:~$ opam install depext
[ERROR] depext unmet availability conditions, e.g. 'opam-version >= "2.0.0~beta5" & opam-version < "2.1"'

**Comment by bitWest11** [comment]
so following the instruction from https://github.com/pizzart/blitter/tree/readme-plus i did manage to finish building it, however west@pop-os:~/flitter$ flitter
Command 'flitter' not found, did you mean:
  command 'flutter' from snap flutter (0+git.ccbc698)
See 'snap info <snapname>' for additional versions.
it just doesn't work now for some reason.

**Comment by NullaOnion** [comment]
The only work around for this I found was running the command "eval $(opam config env)" in terminal before trying to open your split file with flitter.

**Comment by alexozer** [comment]
I rewrote Flitter from scratch, and this is no longer an issue
