### ISSUE TITLE
Error: failed to read split file due to split name count not matching gold count

### ISSUE THREAD

**Issue by WiFiBills** [alexozer/flitter#50]
Hello, 

Whenever I try to set up my splits for a game that I play, it does not launch due to split name count not matching gold count. But I've double counted over and over and it matches with my split names. I can't tell if it's user error or if there is something truly wrong. 
[splits1.json](https://github.com/user-attachments/files/17093728/splits1.json)

This is my .json file for the splits:
{
  "title": "Hotline Miami 2: Wrong Number",
  "category": "NG+ Any%",
  "attempts": 18,
  "completed": 3,
  "split_names": [
    "Down Under",
    "Homicide",
    "Hard News",
    "Final Cut",
    "First Trial",
    "Moving Up",
    "No Mercy",
    "Execution",
    "Ambush",
    "Into The Pit",
    "Dead Ahead",
    "Death Wish",
    "Subway",
    "Stronghold",
    "Withdrawal",
    "Casualties",
    "First Blood",
    "Demolition",
    "House Call",
    "Release",
    "Seizure",
    "Blood Money",
    "Caught",
    "Take Over",
    "Apocalypse"
],
  "golds": [
    {
      "duration": "27.901" 
    },
    {
      "duration": "39.937" 
    },
    null,
    {
      "duration": "59.260"
    },
    {
      "duration": "1:26.814" 
    },
    {
      "duration": "1:10.572" 
    },
    {
      "duration": "1:13.264"
    },
    {
      "duration": "1:20.610"  
    },
    {
      "duration": "1:14.929"
    },
    {
      "duration": "1:09.541"
    },
    {
      "duration": "28.031"
    },
    {
      "duration": "2:15.147"
    },
    {
      "duration": "3:47.346"
    },
    {
      "duration": "55.592"
    },
    {
      "duration": "0.000"
    },
    {
      "duration": "0.000"
    },
    {
      "duration": "0.000"
    },
    {
      "duration":"38.534"
    },
    {
      "duration": "1:00.933"
    },
    {
      "duration": "49.939"
    },
    {
      "duration": "2:49.875"
    },
    {
      "duration": "1:21.391"
    },
    {
      "duration": "1:48.268"
    },
    {
      "duration": "1:21.662"
    },
    {
      "duration": "0.000"
    },
    {
      "duration": "0.000"
    }
  ],
  "personal_best": {
    "attempt": 18,
    "splits": [
      {
        "time": "27.901"
      },
      {
        "time": "1:07.837"
      },
      {
        "time": "2:18.846"
      },
      {
        "time": "3:45.661"
      },
      {
        "time": "4:56.232"
      },
      {
        "time": "6:09.496"
      },
      null,
      {
        "time": "7:37.228"
      },
      {
        "time": "8:52.157"
      },
      {
        "time": "10:05.019"
      },
      {
        "time": "10:33.050"
      },
      {
        "time": "12:48.198"
      },
      {
        "time": "16:35.545"
      },
      {
        "time": "0.000"
      },
      {
        "time": "0.000"
      },
      {
        "time": "0.000"
      },
      {
        "time": "0.000"
      },
      {
        "time": "24:59.738"
      },
      {
        "time": "26:10.718"
      },
      {
        "time": "27:00.657"
      },
      {
        "time": "29:50.533"
      },
      {
        "time": "31:16.239"
      },
      {
        "time": "33:04.507"
      },
      {
        "time": "34:29.910"
      },
      {
        "time": "0.000"
      },
      {
        "time": "40:23.238"
      }
    ]
  }
}

**Comment by alexozer** [comment]
I'm counting 25 split names and 26 golds, including the null gold. Maybe you're forgetting the null?

**Comment by WiFiBills** [comment]
Apologies yeah I deleted that line but now I am having a rust error:
thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/time.rs:1151:31:
overflow when subtracting durations
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How should I proceed? I am not familiar with rust. If it is easier, how would I make new splits with no personal bests or gold times?

**Comment by ComplexPlane** [comment]
This is due to some of your PB splits being zero, you should use null for skipped splits instead. Also make sure that your golds aren't larger than the corresponding times in your PB.

I've added some of the mentioned checks in the loader code as well (unreleased atm)

**Comment by alexozer** [comment]
This is due to some of your PB splits being zero, you should use null for skipped splits instead. Also make sure that your golds aren't larger than the corresponding times in your PB.

I've added some of the mentioned checks in the loader code as well (unreleased atm)

**Comment by alexozer** [comment]
@WiFiBills Is this still an issue?

**Comment by alexozer** [comment]
Assuming this is resolved, closing
